
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
# source = ~/.config/hypr/windows.conf
# source = ~/.config/hypr/decorations.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keyboard.conf
# source = ~/.config/hypr/gestures.conf
# source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/Plugins/hyprcursors.conf
source = ~/.config/hypr/Plugins/hyprspace.conf
# source = ~/.config/hypr/Plugins/hyprsunset.conf