env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = EDITOR,nano
exec-once = hyprlauncher -d
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = hyprpm -n reload 
exec-once = kitty
exec-once = clipse -listen
exec-once = quickshell -c ~/.config/quickshell/StatusBar/
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
