
# Custom window rules

windowrule { # Clipse
    name = clipse-rule
    match:class = kitty
    match:title = clipse
    size = 600 400
    float = true
    center = true
    xray = false
}

windowrule { # battop
    name = battop-rule
    match:class = kitty
    match:title = battop
    size = 600 400
    float = true
    center = true
    xray = false
}

windowrule { # Network manager gui
    name = nm-rule
    match:class = nm-connection-editor
    size = 600 400
    float = true
    center = true
    xray = false
}

layerrule { # quickshell blur 
    name = quickshell-rule
    match:namespace = qsstatusbar
    blur = true
    ignore_alpha = 0.1
    xray = false
}

windowrule { # Supress fullscreen
    name = suppress-maximise-rule
    match:class=*
    suppress_event = fullscreen
}

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

source = ~/.config/hypr/Themes/mocha.conf

general {
    gaps_in = 17
    gaps_out = 20

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba($maroonAlphaee) rgba($greenAlphaee) 45deg
    col.inactive_border = rgba($surface2Alphaff)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = master # can be: scrolling, dwindle, master
    # https://github.com/hyprwm/hyprland-plugins/tree/main/hyprscrolling
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    animate_mouse_windowdragging = true
    enable_swallow = false
}
