{ config, lib, ... }:

{
    options.core.system.security.hardenUSB = {
        enable = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Enable hardening of USB ports via usbguard";
        };
        rules = lib.mkOption {
            type = lib.types.str;
            description = "String for hardening of USB ports via usbguard rules generated by usbgaurd generate-policy";
        };
    };

    config = {
        services.usbguard = {
            enable = config.core.system.security.hardenUSB.enable;
            rules = config.core.system.security.hardenUSB.rules;
        };
    };
}